name: Events Demo 1
on:
  pull_request:
    types: [opened, synchronize]
    # we can also use this way
      # - opened
      # - synchronize
      # will work for targeting branch
    branches:
      - main
      # * - any charackters other than slashes
      - 'dev-*'
      # ** - any charackters including slashes
      - 'feature/**'
    # if pr or commit changes files in a specific folder
    paths: 'src'
  workflow_dispatch:
  push:
    # filter supports for push and pull_request events
    # only these branches would trigger the workflow
    branches:
      - main
      - master
      # * - any charackters other than slashes
      - 'dev-*'
      # ** - any charackters including slashes
      - 'feature/**'
    # if pr or commit changes files not in a specific folder
    paths-ignore: '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."